### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by frasertweedale** [romanofski/purebred#1]
We need to choose a license for purebred

**Comment by frasertweedale** [comment]
My vote is for AGPL.  Given it is end-user software we can maximise benefit of ensuring modified
versions remain free when distributed or used in provision of networked services, but folks will
be unlikely to be annoyed about license compatibility issues.

OTOH if there are parts that seem to be independently useful we could discuss carving them out
as separate libraries and deciding on licensing at that time.

**Comment by romanofski** [comment]
Actually had to read up on the differences first, but it seems fine to me. Do you mean networked services as in running a potentially modified version of the client on a server as a service?

**Comment by frasertweedale** [comment]
Yes.  The AGPL expands the meaning of "convey" to include "use the software or part of the software in or as a network server" (paraphrase).

**Comment by romanofski** [comment]
Do you have a particular version in mind or just take the latest AGPLv3?

**Comment by frasertweedale** [comment]
There is only AGPLv3.
